#pragma once

enum Timeouts : int {
  STATE_TIMEOUT_SECONDS = 7,
  BUFFER_TIMEOUT_SECONDS = 1,
  PING_PONG_TIMEOUT_SECONDS = 2,
  FIRST_JOIN_TIMEOUT_SECONDS = 15,
  SECOND_JOIN_TIMEOUT_SECONDS = 15,
  PLAYER_SELECTION_TIMEOUT_SECONDS = 11,
  STALE_MATCH_TIMEOUT_SECONDS = 30,
  EVENT_ACTION_TIMEOUT_SECONDS = 7,
  START_INNINGS_TIMEOUT_SECONDS = 40,
  END_BALL_TIMEOUT_SECONDS = 20,
};

